name: 2. Run automated tests for a react application
# Trigger for this workflow is whenever a new item is pushed in the repo.
on:
  push:
    # Adding specific paths on which this workflow should be triggered.
    paths:
      - 'react-app-automation-testing/**'
      - '.github/workflows/2_react_app_automation_test.yaml'
  # We can have multiple events for a workflow.
  workflow_dispatch:

jobs:
  automation-test:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install repo on runner
        # Using a pre existing runner to install a repo
        # By default the repo name is picked using ${{ github.repositoy }}
        uses: actions/checkout@v4
      - name: Install nodejs version 18
        uses: actions/setup-node@v4
        # Adding custom config values to this predefined action
        with:
          node-version: 18
      - name: Install other dependencies with versions locked in package.json
        run: npm ci
        # If working directory is not specified it picks up current working directory.
        working-directory: ./react-app-automation-testing
      - name: Run the automation tests
        run: npm test
        working-directory: ./react-app-automation-testing
