name: "4. Lint, test and build an application + have a job for issue event"
on: 
  push:
    paths:
      - "app-test-build-issue/**"
      - ".github/workflows/4_app_test_build_issue.yaml"
  issues:
    types: [opened,edited]
jobs:
  lint-test-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Install nodejs version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Other dependencies
        run: npm ci
        working-directory: ./app-test-build-issue
      - name: Lint
        run: npm run lint
        working-directory: ./app-test-build-issue
      - name: Test
        run: npm run test
        working-directory: ./app-test-build-issue
  deploy-post-test-on-push:
      if: github.event_name == 'push'
      needs: lint-test-on-push
      runs-on: ubuntu-24.04-arm
      steps:
        - name: Fetch repository
          uses: actions/checkout@v4
        - name: Install nodejs version 18
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Other dependencies
          run: npm ci
          working-directory: ./app-test-build-issue
        - name: Build
          run: npm run build
          working-directory: ./app-test-build-issue
  issue-job-context:
    if: github.event_name == 'issues'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Print issue object context
        run: echo "${{ toJSON(github) }}"
      - name: Print the issue created
        run: echo "${{ toJSON(github.event.issue.body) }}"

